schema_version: 20180708
name: fn-weather
version: 0.0.1
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.85
run_image: fnproject/fn-java-fdk:jdk9-1.0.85
cmd: com.example.fn.HelloFunction::handleRequest
format: http-stream
triggers:
- name: fn-weather-trigger
  type: http
  source: /fn-weather-trigger
