schema_version: 20180708
name: fn-weather
version: 0.0.1
runtime: java
cmd: com.example.fn.HelloFunction::handleRequest
format: http-stream
triggers:
- name: fn-weather-trigger
  type: http
  source: /fn-weather-trigger
